
service: SLS-GithubToS3

custom:
  # Provide Github Personal Access Token here
  # https://github.com/settings/tokens
  gts3_config: ${file(./config/github_token.json):${opt:aws-profile}}

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 30
  # Stage name goes here (eg: dev/prod/v1)
  stage: v1
  # Make sure this matches the region you are using
  region: us-east-1

  iamRoleStatements:
    # Required to be able to sync files from the repo to the S3 bucket
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetBucketLocation"
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:DeleteObject"
      # List all S3 buckets this should have permissions to deploy to below
      Resource: ${self:custom.gts3_config.s3_targets}
    # Uncomment the below if you already have an errorLogs table in dynamoDB
    # (Note) Need to document errorLogs some day
    - Effect: "Allow"
      Action:
        - "dynamodb:DescribeTable"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:dynamodb:us-west-2'
            - Ref: 'AWS::AccountId'
            - 'table/errorLogs'

# Define Lambda functions
functions:
  # Deployer function
  deployer:
    handler: src/handler.deployer
    description: Lambda bot triggered by Github webhook to APIG to deploy to S3
    environment:
      GITHUB_WEBHOOK_SECRET: ${self:custom.gts3_config.github_webhook_secret}
      GITHUB_PERSONAL_ACCESS_TOKEN: ${self:custom.gts3_config.github_personal_access_token}
    events:
      - http:
          path: ghWebhook
          method: post
          cors: true
